<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NTH95-20230619Y" failures="0" tests="5" name="Default test" time="0.247" errors="0" timestamp="2024-08-01T13:53:52 ICT">
  <testcase classname="com.api.auto.testcase.TC_API_CreateWork" name="@BeforeClass init" time="0.046">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;io.restassured.response.ResponseBody.asString()&amp;quot; because &amp;quot;com.api.auto.testcase.TC_API_Login.resBody&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.ResponseBody.asString()" because "com.api.auto.testcase.TC_API_Login.resBody" is null
at com.api.auto.testcase.TC_API_Login.T03_ValidateToken(TC_API_Login.java:65)
at com.api.auto.testcase.TC_API_CreateWork.init(TC_API_CreateWork.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- @BeforeClass init -->
  <testcase classname="com.api.auto.testcase.TC_API_CreateWork" name="@AfterClass aftertest" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass aftertest -->
  <testcase classname="com.api.auto.testcase.TC_API_CreateWork" name="Tc01_Validate201Created" time="0.001">
    <skipped/>
  </testcase> <!-- Tc01_Validate201Created -->
  <testcase classname="com.api.auto.testcase.TC_API_CreateWork" name="Tc02_ValidateWorkId" time="0.001">
    <skipped/>
  </testcase> <!-- Tc02_ValidateWorkId -->
  <testcase classname="com.api.auto.testcase.TC_API_CreateWork" name="Tc03_ValidateNameOfWorkMatched" time="0.001">
    <skipped/>
  </testcase> <!-- Tc03_ValidateNameOfWorkMatched -->
  <testcase classname="com.api.auto.testcase.TC_API_CreateWork" name="Tc04_ValidateExperienceMatched" time="0.0">
    <skipped/>
  </testcase> <!-- Tc04_ValidateExperienceMatched -->
  <testcase classname="com.api.auto.testcase.TC_API_CreateWork" name="Tc05_ValidateEducationMatched" time="0.0">
    <skipped/>
  </testcase> <!-- Tc05_ValidateEducationMatched -->
</testsuite> <!-- Default test -->
